using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using WMSWebAPI.Models.V1.Request;

namespace WMSWebAPI.Models.V1.Request
{
    public class WebSubscription
    {
        public string SubscriptionHeadId { get; set; }
        public string CompanyName { get; set; }
        public string CompanyId { get; set; }
        public string Email { get; set; }
        public string phone { get; set; }
        public string Address { get; set; }
        public string ContactPerson { get; set; }
        public string City { get; set; }
        public string state { get; set; }
        public string ZipCode { get; set; }
        public string country { get; set; }
        public string SubscriptionType { get; set; }
        public string SubscriptionTypeId { get; set; }
        public string NoOfUsers { get; set; }
        public string NoOfWarehouse { get; set; }
        public string TaxType { get; set; }
        public string TaxId { get; set; }
        public string PackagePeriod { get; set; }
    }

    public class GetPaymentDetailsSaveRequest
    {
        public string CustSubHeadId { get; set; }
        public string PackageId { get; set; }
        public string TransactionType { get; set; }
        public string TotalUsers { get; set; }
        public string AdditionalUsers { get; set; }
        public string SubTotal { get; set; }
        public string CouponId { get; set; }
        public string DiscountInPercent { get; set; }
        public string Discount { get; set; }
        public string TaxInPercent { get; set; }
        public string TaxNetPayment { get; set; }
        public string TransactionId { get; set; }
        public string TransactionStatus { get; set; }
        public string TransactionBy { get; set; }

    }


    public class UpdateCustSubscriptionHeadRequest
    {
        public string CompanyId { get; set; }
        public string NoOfUsers { get; set; }
        public string NoOfWarehouse { get; set; }
    }

    public class UpdatePaymentDetailsRequest    {        public string ID { get; set; }        public string CustSubHeadId { get; set; }        public string TransactionId { get; set; }        public string TransactionReference { get; set; }        public string TransactionStatus { get; set; }        public string TransactionBy { get; set; }    }

    public class GetCouponIDRequest
    {
        public string CouponCode { get; set; }
    }

    public class CustomerDetailListRequest
    {
        public string ID { get; set; }
    }

    public class SendEmailOtpRequest
    {
        public string Email { get; set; }
        // Commented as OTP is autogenerated by system... 
        // public string OTP { get; set; }
    }

    public class SendSMSOtpRequest
    {
        public string Mobile { get; set; }
        public string OTP { get; set; }
    }


    public class EmailOtpVerificationRequest
    {
        public string Email { get; set; }
        public string OTP { get; set; }
    }

    public class MobileOtpVerificationRequest
    {
        public string Mobile { get; set; }
        public string OTP { get; set; }
    }

    public class CheckUserNameAvailability
    {
        public string UserName { get; set; }
    }

    public class RazorPayClientCreateOrderRequest
    {
        public string ApiKey { get; set; }
        public string Amount { get; set; }
        public string Receipt { get; set; }
        public string Currency { get; set; }
    }

    public class GetSubscriptionPaymentListRequest
    {
        public string CompanyId { get; set; }
        public string UserId { get; set; }
    }

    public class GetSubscriptionTaxListRequest
    {
        public string PlanId { get; set; }
    }
}
